name: Docker

on:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 5433
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: login Docker
      uses: docker/login-action@v3.0.0
      with: 
        username: gustavogoncalvestarraf
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
      
    - name: setup Docker build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./DockerFile
        push: true
        tags: gustavogoncalves/go_ci:${{ github.ref_name }}
